### ISSUE TITLE
Feature request + small bug report

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ijgnd/anki21__remove_linebreaks__do_word_wrap#1]
Hi,

Is it possible to mention in the text hoover that Shift undoes whole text linekreak-removing ? I tried to to a PR but wasn't sure about correct strring formating so I prefered not to break anything :/

Also, if I press Shift+click to undo after a "text selection" edition (as opposed to whole text), I loose the unselected part of the text. 

Thanks for the addon!

**Comment by ijgnd** [comment]
undo with the old version depended on whether text was selected (then Ctrl+Z) or the whole field was affected (then shift+click on button).

I just uploaded a new version to ankiweb that hopefully is simpler to use: undo always works with Ctrl/Cmd+Z. The shift+click is no longer needed.

Could you update and let me know if it works for you? If it works for you I'll adjust the description on ankiweb. Otherwise I'll reverse to the oldversion on ankiweb.

**Comment by thiswillbeyourgithub** [comment]
It works perfectly, thanks a lot!

**Comment by ijgnd** [comment]
Could you update again and test again: I changed the code once more so that removing linebreaks no longer removes formatting (such as bold). Let me know if you run into problems. Thanks.

**Comment by thiswillbeyourgithub** [comment]
Hi,
I think I downloaded both versions at the same time as I don't recall doing the update twice. Anyway it works fine right now.
